Tripeace.Application/Tripeace.Application/Areas/Admin/ViewModels/Shared/AjaxFeedbackViewModel.cs
namespace Tripeace.Application.Areas.Admin.ViewModels.Shared
{
    public class AjaxFeedbackViewModel
    {
        public string Title { get; set; }
        public string Message { get; set; }
        public bool Success { get; set; }
    }
}

Tripeace.Application/Tripeace.Application/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tripeace.Application.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin")]
    [Authorize(Roles = "GameMaster, God")]
    public class DashboardController : Controller
    {
        public DashboardController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Tripeace.Application/Tripeace.Application/Areas/Admin/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Tripeace.Application.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/[controller]")]
    [Authorize(Roles = "GameMaster, God")]
    public class SettingController : Controller
    {
        [HttpGet]
        [Route("[action]")]
        [Authorize(Roles = "GameMaster, God")]
        public IActionResult AdminSettings()
        {
            return View();
        }

        [HttpGet]
        [Route("[action]")]
        [Authorize(Roles = "GameMaster, God")]
        public IActionResult WebsiteSettings()
        {
            return View();
        }
    }
}

Tripeace.Application/Tripeace.Application/Areas/Admin/Views/Shared/_Alerts.cshtml
@if (!ViewData.ModelState.IsValid && ViewData.ModelState.Where(x => x.Key == string.Empty).Count() > 0)
{
    /* Error Alert */

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div class="alert alert-danger">
                <strong>
                    <i class="fa fa-warning"></i>
                    @Localizer["Warning!"]
                </strong>
                <div asp-validation-summary="ModelOnly" style="margin-top: 10px;"></div>
            </div>
        </div>
    </div>
}

@if (ViewData["SuccessMessage"] != null &&
    !String.IsNullOrEmpty(ViewData["SuccessMessage"].ToString()))
{
    /* Success Alert */

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div class="alert alert-success">
                <strong>
                    <i class="fa fa-check-circle"></i>
                    @Localizer["Success"]
                </strong>
                &nbsp;@ViewData["SuccessMessage"]
            </div>
        </div>
    </div>
}

Tripeace.Application/Tripeace.Application/Areas/Admin/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" />

    <environment names="Development">
        <link rel="stylesheet" href="~/Areas/Admin/css/site.css" />
    </environment>

    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/Areas/User/css/site.min.css" asp-append-version="true" />
    </environment>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/locales/bootstrap-datepicker.pt-BR.min.js" charset="UTF-8"></script>

    <environment names="Development">
        <script type="text/javascript" src="~/Areas/Admin/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment names="Staging,Production">
        <script type="text/javascript" src="~/Areas/Admin/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @Html.Raw(JavaScriptSnippet.FullScript)
</head>

<body>
    <input id="website-selected-language" type="hidden" value="@requestCulture?.RequestCulture.Culture.Name" />
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Dashboard")">@ServerInfo.Name</a>
            </div>

            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Striter</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Striter</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Striter</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">Ver todas</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>&nbsp;&nbsp;@Context.User.Identity.Name <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Index", "Home", new { @area = null as string })"><i class="fa fa-fw fa-arrow-circle-o-right"></i> Exit dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li id="dashboard">
                        <a asp-area="Admin" 
                           asp-controller="Dashboard" 
                           asp-action="Index">
                            <i class=" fa fa-fw fa-dashboard"></i> 
                            @Localizer["Dashboard"]
                        </a>
                    </li>
                    <li id="accounts">
                        <a asp-area="Admin" 
                           asp-controller="Account" 
                           asp-action="List">
                            <i class=" fa fa-fw fa-users"></i> 
                            @Localizer["Accounts"]
                        </a>
                    </li>
                    <li id="posts">
                        <a asp-area="Admin" 
                           asp-controller="Post" 
                           asp-action="List">
                            <i class=" fa fa-fw fa-edit"></i> 
                            @Localizer["Posts"]
                        </a>
                    </li>
                    <li id="comments">
                        <a href="#">
                            <i class="fa fa-fw fa-comments"></i> 
                            @Localizer["Comments"]
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#settings"><i class="fa fa-fw fa-arrows-v"></i> @Localizer["Settings"]</a>
                        <ul id="settings" class="collapse">
                            <li id="admin-settings">
                                <a asp-area="Admin"
                                   asp-controller="Setting"
                                   asp-action="@(nameof(Tripeace.Application.Areas.Admin.Controllers.SettingController.AdminSettings))">
                                    <i class="fa fa-fw fa-wrench"></i>
                                        @Localizer["AdminSettings"]
                                </a>
                            </li>
                            <li>
                                <a asp-area="Admin"
                                   asp-controller="Setting"
                                   asp-action="@(nameof(Tripeace.Application.Areas.Admin.Controllers.SettingController.WebsiteSettings))">
                                    <i class="fa fa-fw fa-wrench"></i>
                                    @Localizer["WebsiteSettings"]
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">
            <div class="container-fluid">

                @RenderSection("featured", required: false)

                @RenderBody()

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

    <div class="modal fade" id="modal-server-response" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="@Localizer["Close"]"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modal-server-response-title"></h4>
                </div>
                <div id="modal-server-response-body" class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@Localizer["Close"]</button>
                </div>
            </div>
        </div>
    </div>

    
    @RenderSection("Scripts", required: false)

</body>
</html>